### PR TITLE
Added em tag

### PR DESCRIPTION
**Pull request by awickham10**
# Pull Request added em tag
Added em tag based on strong tag function.

### Please tell us , the type of Change you are submitting:
Select one of the following: 
- [ ] Bug
- [ ] Feature
- [x] Minor Change

### Does it fix an existing issue? Please tell us which one
Contributes to issue #7.

### Description of what's been changed
Added em.ps1 function and tests.

### Results of your tests (If applicable)
image

### CODE REVIEW

**Comment by awickham10** [comment]
Is this more what you were thinking?

```powershell
    .SYNOPSIS
    Generates em HTML tag.

    .Description
    This tag is a phrase tag. It renders as emphasized text.

    .EXAMPLE
    p{
        "This is";em {"cool"}
    }

    Will generate the following code

    <p>
        This is
        <em>
        cool
        </em>
    </p>
```

**Comment by Stephanevg** [comment]
Yeah, that is great!
One very last thing, and then I'll merge: Could you change the $Content parameter from `mandatory=$true` to $false?

I think we should leave the possibility for the end user to set an em element with an empty value. (and modified using Javascript in a later step for example).
Thanks!

**Comment by awickham10** [comment]
Done!

**Comment by Stephanevg** [comment]
Awesome, Thanks a lot for your PR @awickham10 !

**Pull request merged**
